// VERBATIM U.S. Investor Disclaimer (team, updated 2026-06-30). Do NOT reword/retitle/restructure.
// The doc title renders from the page header; this body starts at the first paragraph.
export const usInvestorDisclaimerMarkdown = `The Tokens have not been registered under the Securities Act of 1933, as amended, or any state securities laws, and are being offered and sold solely to persons who qualify as “accredited investors” within the meaning of Rule 501(a) of Regulation D under the Securities Act. Each purchaser must represent and warrant that it is an accredited investor, is acquiring the Tokens for its own account and not with a view to resale or distribution, and has sufficient knowledge and experience in financial and business matters to evaluate the merits and risks of the purchase.

The purchaser acknowledges that the Tokens may be deemed to be “securities” under U.S. federal or state securities laws, and that no governmental authority has passed upon or endorsed the merits of the offering or the accuracy or adequacy of the offering materials. The Tokens are subject to significant transfer restrictions and may not be offered, sold, pledged, transferred or otherwise disposed of except pursuant to an effective registration statement or an available exemption from registration under applicable securities laws. The purchaser should be prepared to bear the economic risk of the purchase for an indefinite period of time.

The Issuer may, in its sole discretion, reject, suspend, cancel, unwind, freeze, or refuse any purchase, acquisition, holding, use, access, or transfer for legal, regulatory, compliance, or other reasons. Nothing on this website or in related materials constitutes legal, tax, accounting, investment, financial, or other professional advice, or any offer, solicitation, recommendation, or invitation to purchase, acquire, hold, use, or transfer any Token.

## Non-US

The Tokens have not been registered under the United States Securities Act of 1933, as amended, or any U.S. state securities laws, and are offered outside the United States in reliance on Regulation S. The Tokens may not be offered, sold, delivered, transferred, assigned, pledged, or otherwise disposed of in the United States or to, or for the account or benefit of, any U.S. person, except pursuant to an available exemption from registration and in compliance with applicable law. Each Investor represents and warrants that it is not a “U.S. person” as defined in Rule 902(k) of Regulation S under the Securities Act of 1933, as amended, and is not acquiring the securities for the account or benefit of any U.S. person. Each Investor further represents that it is located outside the United States, was not offered the securities while in the United States, and is acquiring the securities in an offshore transaction in reliance on Regulation S. For purposes of this Agreement, “U.S. person” has the meaning set forth in Rule 902(k) of Regulation S, and any person who is not a U.S. person shall be deemed a “non-U.S. person.”

The Issuer may, in its sole discretion, reject, suspend, cancel, unwind, freeze, or refuse any purchase, acquisition, holding, use, access, or transfer for legal, regulatory, compliance, or other reasons. The Tokens may be deemed securities or other regulated instruments, and no representation or warranty is made that any exemption or regulatory treatment will be available. Nothing on this website or in related materials constitutes legal, tax, accounting, investment, financial, or other professional advice, or any offer, solicitation, recommendation, or invitation to purchase, acquire, hold, use, or transfer any Token. By accessing this website or acquiring, holding, using, or transferring any Token, each person represents, warrants, acknowledges, and agrees that such person is not located in the United States and is not a U.S. person, unless expressly approved by the Issuer under an available exemption; if so approved, such person is an accredited investor; such person assumes the risk of total loss; and no transfer shall occur except in accordance with applicable law and Issuer restrictions. The Issuer may implement geoblocking, wallet screening, KYC/AML procedures, sanctions screening, investor verification, holding periods, legends, transfer controls, and other compliance measures, and may restrict, suspend, terminate, or cancel access or participation at any time without liability. Participation involves substantial risk, including total loss, limited or no liquidity, volatility, operational, technological, cybersecurity, smart-contract, protocol, tax, legal, regulatory, and enforcement risks. Persons located in the United States, U.S. persons, and persons who do not satisfy all eligibility requirements must not access, purchase, acquire, hold, use, or transfer the Tokens.`
